FROM python:3.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY requirements.backend.txt ./

RUN pip install --no-cache-dir -r requirements.backend.txt

COPY backend ./backend
COPY bot ./bot
COPY migrations ./migrations
COPY alembic.ini ./

WORKDIR /app/backend

EXPOSE 8000

CMD exec uvicorn app.main:app --host 0.0.0.0 --port 8000
